[project]
name = "replicator-git-sync"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "dulwich>=0.24.1",
    "fastapi[standard]>=0.116.1",
    "pydantic>=2.11.7",
]

[dependency-groups]
dev = ["workers-py"]
